#all users
GET https://cse341-project1-e2i6.onrender.com/contacts

#single user
GET https://cse341-project1-e2i6.onrender.com/contacts/672d38a9dd7bc01d62629d3b

GET https://cse341-project1-e2i6.onrender.com/contacts/672d3a8add7bc01d62629d3c

GET https://cse341-project1-e2i6.onrender.com/contacts/672d3a8add7bc01d62629d3c

GET https://cse341-project1-e2i6.onrender.com/contacts/672d3ae6dd7bc01d62629d3d


