# Get all contacts
GET http://localhost:4888/contacts

# Get contact by ID
GET http://localhost:4888/contacts/672d38a9dd7bc01d62629d3b
GET http://localhost:4888/contacts/672d3a8add7bc01d62629d3c
GET http://localhost:4888/contacts/672d3ae6dd7bc01d62629d3d

# Create a new contact
POST http://localhost:4888/contacts
Content-Type: application/json

{
    "firstName": "New",
    "lastName": "Contact",
    "email": "new.contact@example.com",
    "favoriteColor": "Blue",
    "birthday": "1990-12-12"
}

# Update a contact by ID
PUT http://localhost:4888/contacts/672d38a9dd7bc01d62629d3b
Content-Type: application/json

{
    "firstName": "Kaitlyn",
    "lastName": "Rowell",
    "email": "kaityrowe15@gmail.com",
    "favoriteColor": "Pink",
    "birthday": "2001-07-27"
}

# Delete a contact by ID
DELETE http://localhost:4888/contacts/672d3ae6dd7bc01d62629d3d
